// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package nadevault

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CsMap struct {
	ID          int16
	Code        string
	DisplayName string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

type Nade struct {
	ID          int64
	Name        string
	Description string
	MapID       int16
	NadeType    interface{}
	CommonSide  interface{}
	FromCallout string
	ToCallout   string
	MouseClick  interface{}
	IsJumping   bool
	IsRunning   bool
	IsWalking   bool
	Images      []byte
	IsPublic    bool
	CreatedBy   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SearchTsv   interface{}
}
