// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package nadevault

import (
	"github.com/Y-Figos/nadevault/internal/domain"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CsMap struct {
	ID          int16
	Code        string
	DisplayName string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

type Nade struct {
	ID           int64
	Name         string
	Description  string
	PublicID     uuid.UUID
	MapID        int16
	NadeType     domain.NadeType
	CommonSide   domain.Side
	FromCallout  string
	ToCallout    string
	MouseClick   domain.MouseClick
	IsJumping    bool
	IsRunning    bool
	IsWalking    bool
	Images       []byte
	ImagesStatus domain.ImageStatus
	IsPublic     bool
	CreatedBy    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SearchTsv    interface{}
}
