// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package nadevault

import (
	"context"

	"github.com/Y-Figos/nadevault/internal/domain"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addNade = `-- name: AddNade :one
INSERT INTO nades (
    name,
    description,
    map_id,
    nade_type,
    common_side,
    from_callout,
    to_callout,
    mouse_click,
    is_jumping,
    is_running,
    is_walking,
    is_public,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
) RETURNING id, public_id
`

type AddNadeParams struct {
	Name        string
	Description string
	MapID       int16
	NadeType    domain.NadeType
	CommonSide  domain.Side
	FromCallout string
	ToCallout   string
	MouseClick  domain.MouseClick
	IsJumping   bool
	IsRunning   bool
	IsWalking   bool
	IsPublic    bool
	CreatedBy   pgtype.Text
}

type AddNadeRow struct {
	ID       int64
	PublicID uuid.UUID
}

func (q *Queries) AddNade(ctx context.Context, arg AddNadeParams) (AddNadeRow, error) {
	row := q.db.QueryRow(ctx, addNade,
		arg.Name,
		arg.Description,
		arg.MapID,
		arg.NadeType,
		arg.CommonSide,
		arg.FromCallout,
		arg.ToCallout,
		arg.MouseClick,
		arg.IsJumping,
		arg.IsRunning,
		arg.IsWalking,
		arg.IsPublic,
		arg.CreatedBy,
	)
	var i AddNadeRow
	err := row.Scan(&i.ID, &i.PublicID)
	return i, err
}

const getMapByCode = `-- name: GetMapByCode :one
SELECT
cs_maps.id, cs_maps.code, cs_maps.display_name, cs_maps.is_active, cs_maps.created_at
FROM cs_maps
WHERE code = $1
`

type GetMapByCodeRow struct {
	CsMap CsMap
}

func (q *Queries) GetMapByCode(ctx context.Context, code string) (GetMapByCodeRow, error) {
	row := q.db.QueryRow(ctx, getMapByCode, code)
	var i GetMapByCodeRow
	err := row.Scan(
		&i.CsMap.ID,
		&i.CsMap.Code,
		&i.CsMap.DisplayName,
		&i.CsMap.IsActive,
		&i.CsMap.CreatedAt,
	)
	return i, err
}

const getMapByID = `-- name: GetMapByID :one
SELECT
cs_maps.id, cs_maps.code, cs_maps.display_name, cs_maps.is_active, cs_maps.created_at
FROM cs_maps
WHERE is_active = true
AND id = $1
`

type GetMapByIDRow struct {
	CsMap CsMap
}

func (q *Queries) GetMapByID(ctx context.Context, id int16) (GetMapByIDRow, error) {
	row := q.db.QueryRow(ctx, getMapByID, id)
	var i GetMapByIDRow
	err := row.Scan(
		&i.CsMap.ID,
		&i.CsMap.Code,
		&i.CsMap.DisplayName,
		&i.CsMap.IsActive,
		&i.CsMap.CreatedAt,
	)
	return i, err
}

const getMaps = `-- name: GetMaps :many
SELECT
cs_maps.id, cs_maps.code, cs_maps.display_name, cs_maps.is_active, cs_maps.created_at
FROM cs_maps
WHERE is_active = true
ORDER BY display_name
`

type GetMapsRow struct {
	CsMap CsMap
}

func (q *Queries) GetMaps(ctx context.Context) ([]GetMapsRow, error) {
	rows, err := q.db.Query(ctx, getMaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMapsRow
	for rows.Next() {
		var i GetMapsRow
		if err := rows.Scan(
			&i.CsMap.ID,
			&i.CsMap.Code,
			&i.CsMap.DisplayName,
			&i.CsMap.IsActive,
			&i.CsMap.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNade = `-- name: GetNade :one
SELECT
nades.id, nades.name, nades.description, nades.public_id, nades.map_id, nades.nade_type, nades.common_side, nades.from_callout, nades.to_callout, nades.mouse_click, nades.is_jumping, nades.is_running, nades.is_walking, nades.images, nades.images_status, nades.is_public, nades.created_by, nades.created_at, nades.updated_at, nades.search_tsv,
cs_maps.id, cs_maps.code, cs_maps.display_name, cs_maps.is_active, cs_maps.created_at
FROM nades
JOIN cs_maps ON nades.map_id = cs_maps.id
WHERE nades.id = $1
`

type GetNadeRow struct {
	Nade  Nade
	CsMap CsMap
}

func (q *Queries) GetNade(ctx context.Context, id int64) (GetNadeRow, error) {
	row := q.db.QueryRow(ctx, getNade, id)
	var i GetNadeRow
	err := row.Scan(
		&i.Nade.ID,
		&i.Nade.Name,
		&i.Nade.Description,
		&i.Nade.PublicID,
		&i.Nade.MapID,
		&i.Nade.NadeType,
		&i.Nade.CommonSide,
		&i.Nade.FromCallout,
		&i.Nade.ToCallout,
		&i.Nade.MouseClick,
		&i.Nade.IsJumping,
		&i.Nade.IsRunning,
		&i.Nade.IsWalking,
		&i.Nade.Images,
		&i.Nade.ImagesStatus,
		&i.Nade.IsPublic,
		&i.Nade.CreatedBy,
		&i.Nade.CreatedAt,
		&i.Nade.UpdatedAt,
		&i.Nade.SearchTsv,
		&i.CsMap.ID,
		&i.CsMap.Code,
		&i.CsMap.DisplayName,
		&i.CsMap.IsActive,
		&i.CsMap.CreatedAt,
	)
	return i, err
}

const getNadeByPublicID = `-- name: GetNadeByPublicID :one
SELECT
nades.id, nades.name, nades.description, nades.public_id, nades.map_id, nades.nade_type, nades.common_side, nades.from_callout, nades.to_callout, nades.mouse_click, nades.is_jumping, nades.is_running, nades.is_walking, nades.images, nades.images_status, nades.is_public, nades.created_by, nades.created_at, nades.updated_at, nades.search_tsv,
cs_maps.id, cs_maps.code, cs_maps.display_name, cs_maps.is_active, cs_maps.created_at
FROM nades
JOIN cs_maps ON nades.map_id = cs_maps.id
WHERE nades.public_id = $1
`

type GetNadeByPublicIDRow struct {
	Nade  Nade
	CsMap CsMap
}

func (q *Queries) GetNadeByPublicID(ctx context.Context, publicID uuid.UUID) (GetNadeByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getNadeByPublicID, publicID)
	var i GetNadeByPublicIDRow
	err := row.Scan(
		&i.Nade.ID,
		&i.Nade.Name,
		&i.Nade.Description,
		&i.Nade.PublicID,
		&i.Nade.MapID,
		&i.Nade.NadeType,
		&i.Nade.CommonSide,
		&i.Nade.FromCallout,
		&i.Nade.ToCallout,
		&i.Nade.MouseClick,
		&i.Nade.IsJumping,
		&i.Nade.IsRunning,
		&i.Nade.IsWalking,
		&i.Nade.Images,
		&i.Nade.ImagesStatus,
		&i.Nade.IsPublic,
		&i.Nade.CreatedBy,
		&i.Nade.CreatedAt,
		&i.Nade.UpdatedAt,
		&i.Nade.SearchTsv,
		&i.CsMap.ID,
		&i.CsMap.Code,
		&i.CsMap.DisplayName,
		&i.CsMap.IsActive,
		&i.CsMap.CreatedAt,
	)
	return i, err
}

const listNadesByMapID = `-- name: ListNadesByMapID :many
SELECT
    nades.id, nades.name, nades.description, nades.public_id, nades.map_id, nades.nade_type, nades.common_side, nades.from_callout, nades.to_callout, nades.mouse_click, nades.is_jumping, nades.is_running, nades.is_walking, nades.images, nades.images_status, nades.is_public, nades.created_by, nades.created_at, nades.updated_at, nades.search_tsv,
    cs_maps.id, cs_maps.code, cs_maps.display_name, cs_maps.is_active, cs_maps.created_at
FROM nades
JOIN cs_maps ON nades.map_id = cs_maps.id
WHERE nades.map_id = $1
  AND (
    $2::text = '' 
    OR nades.search_tsv @@ plainto_tsquery('simple', $2)
  )
ORDER BY nades.created_at DESC
LIMIT $4 OFFSET $3
`

type ListNadesByMapIDParams struct {
	MapID  int16
	Query  string
	Offset int32
	Limit  int32
}

type ListNadesByMapIDRow struct {
	Nade  Nade
	CsMap CsMap
}

func (q *Queries) ListNadesByMapID(ctx context.Context, arg ListNadesByMapIDParams) ([]ListNadesByMapIDRow, error) {
	rows, err := q.db.Query(ctx, listNadesByMapID,
		arg.MapID,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNadesByMapIDRow
	for rows.Next() {
		var i ListNadesByMapIDRow
		if err := rows.Scan(
			&i.Nade.ID,
			&i.Nade.Name,
			&i.Nade.Description,
			&i.Nade.PublicID,
			&i.Nade.MapID,
			&i.Nade.NadeType,
			&i.Nade.CommonSide,
			&i.Nade.FromCallout,
			&i.Nade.ToCallout,
			&i.Nade.MouseClick,
			&i.Nade.IsJumping,
			&i.Nade.IsRunning,
			&i.Nade.IsWalking,
			&i.Nade.Images,
			&i.Nade.ImagesStatus,
			&i.Nade.IsPublic,
			&i.Nade.CreatedBy,
			&i.Nade.CreatedAt,
			&i.Nade.UpdatedAt,
			&i.Nade.SearchTsv,
			&i.CsMap.ID,
			&i.CsMap.Code,
			&i.CsMap.DisplayName,
			&i.CsMap.IsActive,
			&i.CsMap.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
