// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package nadevault

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNade = `-- name: GetNade :one
SELECT
id,
name,
description,
map_id,
nade_type,
common_side,
from_callout,
to_callout,
mouse_click,
is_jumping,
is_running,
is_walking,
images,
is_public,
created_by,
created_at,
updated_at
FROM nades
WHERE id = $1
`

type GetNadeRow struct {
	ID          int64
	Name        string
	Description string
	MapID       int16
	NadeType    interface{}
	CommonSide  interface{}
	FromCallout string
	ToCallout   string
	MouseClick  interface{}
	IsJumping   bool
	IsRunning   bool
	IsWalking   bool
	Images      []byte
	IsPublic    bool
	CreatedBy   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetNade(ctx context.Context, id int64) (GetNadeRow, error) {
	row := q.db.QueryRow(ctx, getNade, id)
	var i GetNadeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MapID,
		&i.NadeType,
		&i.CommonSide,
		&i.FromCallout,
		&i.ToCallout,
		&i.MouseClick,
		&i.IsJumping,
		&i.IsRunning,
		&i.IsWalking,
		&i.Images,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
