// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package nadevault

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNade = `-- name: AddNade :one
INSERT INTO nades (
    name,
    description,
    map_id,
    nade_type,
    common_side,
    from_callout,
    to_callout,
    mouse_click,
    is_jumping,
    is_running,
    is_walking,
    is_public,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
) RETURNING id, public_id
`

type AddNadeParams struct {
	Name        string
	Description string
	MapID       int16
	NadeType    string
	CommonSide  string
	FromCallout string
	ToCallout   string
	MouseClick  string
	IsJumping   bool
	IsRunning   bool
	IsWalking   bool
	IsPublic    bool
	CreatedBy   pgtype.Text
}

type AddNadeRow struct {
	ID       int64
	PublicID string
}

func (q *Queries) AddNade(ctx context.Context, arg AddNadeParams) (AddNadeRow, error) {
	row := q.db.QueryRow(ctx, addNade,
		arg.Name,
		arg.Description,
		arg.MapID,
		arg.NadeType,
		arg.CommonSide,
		arg.FromCallout,
		arg.ToCallout,
		arg.MouseClick,
		arg.IsJumping,
		arg.IsRunning,
		arg.IsWalking,
		arg.IsPublic,
		arg.CreatedBy,
	)
	var i AddNadeRow
	err := row.Scan(&i.ID, &i.PublicID)
	return i, err
}

const getMapByCode = `-- name: GetMapByCode :one
SELECT
id,
code,
display_name,
is_active,
created_at
FROM cs_maps
WHERE code = $1
`

func (q *Queries) GetMapByCode(ctx context.Context, code string) (CsMap, error) {
	row := q.db.QueryRow(ctx, getMapByCode, code)
	var i CsMap
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getMapByID = `-- name: GetMapByID :one
SELECT
id,
code,
display_name,
is_active,
created_at
FROM cs_maps
WHERE is_active = true
AND id = $1
`

func (q *Queries) GetMapByID(ctx context.Context, id int16) (CsMap, error) {
	row := q.db.QueryRow(ctx, getMapByID, id)
	var i CsMap
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getMaps = `-- name: GetMaps :many
SELECT
id,
code,
display_name,
is_active,
created_at
FROM cs_maps
WHERE is_active = true
ORDER BY display_name
`

func (q *Queries) GetMaps(ctx context.Context) ([]CsMap, error) {
	rows, err := q.db.Query(ctx, getMaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CsMap
	for rows.Next() {
		var i CsMap
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DisplayName,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNade = `-- name: GetNade :one
SELECT
nades.id,
cs_maps.display_name AS map_display_name,
name,
description,
map_id,
nade_type,
common_side,
from_callout,
to_callout,
mouse_click,
is_jumping,
is_running,
is_walking,
images,
is_public,
created_by,
nades.created_at,
updated_at
FROM nades
JOIN cs_maps ON nades.map_id = cs_maps.id
WHERE nades.id = $1
`

type GetNadeRow struct {
	ID             int64
	MapDisplayName string
	Name           string
	Description    string
	MapID          int16
	NadeType       string
	CommonSide     string
	FromCallout    string
	ToCallout      string
	MouseClick     string
	IsJumping      bool
	IsRunning      bool
	IsWalking      bool
	Images         []byte
	IsPublic       bool
	CreatedBy      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetNade(ctx context.Context, id int64) (GetNadeRow, error) {
	row := q.db.QueryRow(ctx, getNade, id)
	var i GetNadeRow
	err := row.Scan(
		&i.ID,
		&i.MapDisplayName,
		&i.Name,
		&i.Description,
		&i.MapID,
		&i.NadeType,
		&i.CommonSide,
		&i.FromCallout,
		&i.ToCallout,
		&i.MouseClick,
		&i.IsJumping,
		&i.IsRunning,
		&i.IsWalking,
		&i.Images,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNadeByPublicID = `-- name: GetNadeByPublicID :one
SELECT
nades.public_id,
cs_maps.display_name AS map_display_name,
name,
description,
map_id,
nade_type,
common_side,
from_callout,
to_callout,
mouse_click,
is_jumping,
is_running,
is_walking,
images,
is_public,
created_by,
nades.created_at,
updated_at
FROM nades
JOIN cs_maps ON nades.map_id = cs_maps.id
WHERE nades.public_id = $1
`

type GetNadeByPublicIDRow struct {
	PublicID       string
	MapDisplayName string
	Name           string
	Description    string
	MapID          int16
	NadeType       string
	CommonSide     string
	FromCallout    string
	ToCallout      string
	MouseClick     string
	IsJumping      bool
	IsRunning      bool
	IsWalking      bool
	Images         []byte
	IsPublic       bool
	CreatedBy      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetNadeByPublicID(ctx context.Context, publicID string) (GetNadeByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getNadeByPublicID, publicID)
	var i GetNadeByPublicIDRow
	err := row.Scan(
		&i.PublicID,
		&i.MapDisplayName,
		&i.Name,
		&i.Description,
		&i.MapID,
		&i.NadeType,
		&i.CommonSide,
		&i.FromCallout,
		&i.ToCallout,
		&i.MouseClick,
		&i.IsJumping,
		&i.IsRunning,
		&i.IsWalking,
		&i.Images,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNadesByMapID = `-- name: ListNadesByMapID :many
SELECT
nades.id,
cs_maps.display_name AS map_display_name,
name,
description,
map_id,
nade_type,
common_side,
from_callout,
to_callout,
mouse_click,
is_jumping,
is_running,
is_walking,
images,
is_public,
created_by,
nades.created_at,
updated_at
FROM nades
JOIN cs_maps ON nades.map_id = cs_maps.id
WHERE map_id = $1
ORDER BY nades.created_at DESC
LIMIT $2 OFFSET $3
`

type ListNadesByMapIDParams struct {
	MapID  int16
	Limit  int32
	Offset int32
}

type ListNadesByMapIDRow struct {
	ID             int64
	MapDisplayName string
	Name           string
	Description    string
	MapID          int16
	NadeType       string
	CommonSide     string
	FromCallout    string
	ToCallout      string
	MouseClick     string
	IsJumping      bool
	IsRunning      bool
	IsWalking      bool
	Images         []byte
	IsPublic       bool
	CreatedBy      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListNadesByMapID(ctx context.Context, arg ListNadesByMapIDParams) ([]ListNadesByMapIDRow, error) {
	rows, err := q.db.Query(ctx, listNadesByMapID, arg.MapID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNadesByMapIDRow
	for rows.Next() {
		var i ListNadesByMapIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MapDisplayName,
			&i.Name,
			&i.Description,
			&i.MapID,
			&i.NadeType,
			&i.CommonSide,
			&i.FromCallout,
			&i.ToCallout,
			&i.MouseClick,
			&i.IsJumping,
			&i.IsRunning,
			&i.IsWalking,
			&i.Images,
			&i.IsPublic,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
