// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Y-Figos/nadevault/internal/domain"

func AddNadeForm(Maps []domain.CsMap) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card\" id=\"card\"><div class=\"card-header\"><div class=\"card-title\">Add Nade</div></div><div class=\"card-body\" id=\"nade-info\"><form method=\"post\" id=\"add-nade-form\" hx-post=\"/admin/nades/new\" hx-target=\"#card\" hx-swap=\"outerHTML\"><div class=\"form-grid\"><div class=\"col-6\"><label for=\"name\">Nade Name</label> <input type=\"text\" id=\"name\" name=\"name\" class=\"input\" required></div><div class=\"col-6\"><label for=\"desc\">Description</label> <textarea id=\"desc\" name=\"desc\" required></textarea></div><div class=\"col-6\"><label for=\"type\">Type</label> <select id=\"type\" name=\"type\" required><option value=\"\">Select type</option> <option value=\"smoke\">Smoke</option> <option value=\"flashbang\">Flash</option> <option value=\"frag\">Frag</option> <option value=\"moly\">Molotov</option></select></div><div class=\"col-6\"><label for=\"map\">Map</label> <select id=\"map_id\" name=\"map_id\" required>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, m := range Maps {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<option value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(m.ID)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/web/templates/addNadeForm.templ`, Line: 34, Col: 55}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(m.DisplayName)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/web/templates/addNadeForm.templ`, Line: 34, Col: 71}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</option>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</select></div><div class=\"col-6\"><label for=\"from\" class=\"from-label\">From</label> <input type=\"text\" id=\"from\" name=\"from\" class=\"input\" required></div><div class=\"col-6\"><label for=\"to\" class=\"to-label\">To</label> <input type=\"text\" id=\"to\" name=\"to\" class=\"input\" required></div><div class=\"col-6\"><label for=\"side\">Side</label> <select id=\"side\" name=\"common_side\" required><option value=\"\">Select side</option> <option value=\"T\">Terrorist</option> <option value=\"CT\">Counter-Terrorist</option></select></div><div class=\"col-6\"><label for=\"mouse_click\">Mouse Click</label> <select id=\"mouse_click\" name=\"mouse_click\"><option value=\"mouse1\">Mouse1</option> <option value=\"mouse2\">Mouse2</option> <option value=\"both\">both</option></select></div><div class=\"col-12 row\"><label class=\"row\"><input type=\"checkbox\" name=\"is_jumping\"> <span>Jump Throw</span></label> <label class=\"row\"><input type=\"checkbox\" name=\"is_running\"> <span>Run Throw</span></label> <label class=\"row\"><input type=\"checkbox\" name=\"is_walking\"> <span>Walk Throw</span></label></div><input type=\"hidden\" name=\"created_by\" value=\"admin_test\"><div class=\"col-12\"><button class=\"btn btn-primary\" type=\"submit\">Save Nade</button></div></div></form></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
